### ISSUE TITLE
Make http/https prettier

### ISSUE THREAD

**Issue by jkingsman** [jkingsman/FreeStep#56]
Add a variable to enable or disable https

**Comment by krisdahl** [comment]
I agree.  Might not be that hard.  If I get it sorted, will try to submit a patch.

**Comment by jkingsman** [comment]
Awesome! I was just envisaging a flag that determines if/how modules are loaded. If you end up submitting a patch, feel free to edit the README too. Thanks!

**Comment by jkingsman** [comment]
@krisdahl any luck on this? No pressure; just curious.

**Comment by jkingsman** [comment]
This feature is low priority; I'm closing it until I have further impetus to pursue it.
