### ISSUE TITLE
auto linking

### ISSUE THREAD

**Issue by Conver** [jkingsman/FreeStep#57]
URLs, email and ftp (etc) links should be converted to hyper link automatically

**Comment by jkingsman** [comment]
That's definitely an intriguing feature; I would be interested to see FTP, http, and magnet protocols supported at least. I'm I'm the middle of finals right now and wouldn't be able to look at this for a few weeks at least but feel free to open a PR!

**Comment by Conver** [comment]
Yep, that would indeed be a good start.

**Comment by jkingsman** [comment]
It now matches FTP, http(s), and magnet. You're benefitting from my last burst of procrastination ;P

**Comment by Conver** [comment]
Hehe perfect!
