### ISSUE TITLE
Highlight message

### ISSUE THREAD

**Issue by Conver** [jkingsman/FreeStep#58]
Highlight message if nickname is in the message

Text could either become an color, or message could get a background color

**Comment by jkingsman** [comment]
I'll look at this later today.

**Comment by Conver** [comment]
Great.

**Comment by Conver** [comment]
Maybe also add an option to only play sound if nickname is in message, 

The 2:
+ Play new message alert when window is focused 
+ Play new message alert when window is unfocused 

Would ofc override this one.

**Comment by jkingsman** [comment]
Yeah I might replace those with a radio button -- "play sound on nickname only" and "play sound on all messages". What do you think about disabling sound when the window is focused?

**Comment by Conver** [comment]
I think disabling the 'Play new message alert when window is focused ' would be a good idea.
I don't think it will be used, since you see the messages if windows is focused.

So yea, remove that one, and replace it with 'play sound on nickname only', and make it radio instead.

**Comment by jkingsman** [comment]
Alright, sounds good. I'm going to implement the highlighting today, and create a new issue for the sound (I'm crunched for time right now).

**Comment by Conver** [comment]
Sure, that is cool! :) The highlight is also more important then the sound is (As I actually think the most don't use it at all)

**Comment by jkingsman** [comment]
Just added the feature; the text is red when you get mentioned.

**Comment by Conver** [comment]
Prefect!

**Comment by jkingsman** [comment]
Options are now covered in the readme, as well as commented in the code. Check out `customMode`, `appName`, and `appByline` in `client.js`.

**Comment by Conver** [comment]
Okay, I'll look up those options.

**Comment by jkingsman** [comment]
Whoops; that last comment was for issue #62.
