### ISSUE TITLE
Share files

### ISSUE THREAD

**Issue by Conver** [jkingsman/FreeStep#59]
Like the images function, it would be nice if it was possible to share files aswell.

I'm not sure how it can be done tho, but should be possible

Images are atm shared with anyone in the room, it would be a huge job to send files to all in the room, so instead could a download link be posted etc

Thoughts?

**Comment by jkingsman** [comment]
The big issue with that is that the files either need to be kept on the server (which is in violation of the "know-nothing/have-nothing" server ethos, or the file is automatically downloaded with JS (I don't like the idea of a file being created on my system without explicit permission), or it sits resident in local storage until downloaded (seems like the best solution, but is less trivial to code). 

I'm not against the idea, it just opens up the system as a little more dangerous to use. Not allowing anything that could be malicious was part of my design; links aren't converted, files are safe embedded images, etc. However, if the community wants more than that, I'm totally happy to work on it when I have time. 

I'm in the middle of finals right now, but I'd be happy to hear your thoughts on implementation, or PR's if you're feeling adventurous.

**Comment by Conver** [comment]
Great.

I'm using this system more than 1 place, so as I get ideas for what could improve the system, then I add them here.

Sadly I'm not the best with JS, more backend i'm into, but I might be able to help out.

I have an JS mate, which understand sharing of file with high-end encryption and P2P, I might point him to this issue, he might have an idea or 2.

**Comment by jkingsman** [comment]
Sure! The encryption is a pretty simple cipher; I'd be thrilled to have someone that knows more crypto than me help me out.

**Comment by Conver** [comment]
Sure, understandable.

I do myself have a lot of experience with cipher/encryption, but sadly not with JS. I'll point him to this, and I'm sure he will help out. he uses the system aswell (On my servers tho), and we love that we can work our development in a secure and private inv.

**Comment by jkingsman** [comment]
Glad to hear you find it useful!

**Comment by Conver** [comment]
It could maybe be done with an form of a plugin or addon

Like, I could create the function in PHP etc, which would be an 'external' page of the chat. (Not accessible)

then, if people wish to use it, they can download the addon, and somehow add some info in the main chat config.

So if those info is set, then it will know where to upload file to, and it would return name, url to dl etc?

Could that be an option?
- I can create the addon in PHP with high-end encryption.

if you like this idea let me know, and we can create a chat room somewhere (You or mine) to talk about how to accomplish this

**Comment by jkingsman** [comment]
Perhaps... sounds hefty. I'm not opposed but definitely want this to be as minimal as possible.

Can you ping me on this again in a week, please?

**Comment by Conver** [comment]
Ofc, that is udnerstandable. and the best is to keep it minimal.
But file sharing would be a big plus, at least for all of those I know using this :)

Sure, I'll ping you later.

**Comment by jkingsman** [comment]
I'm going to go ahead and close this issue as it is not a feature I will be adding any time soon - feel free to fork, though!
