### ISSUE TITLE
option to show or not show images

### ISSUE THREAD

**Issue by Conver** [jkingsman/FreeStep#60]
Images are shared with anyone right now, but would it be possible to make an option so opt out of those?

So if I example doesn't want to see the images, then I can opt out on it, in the option panel, and then the images will not be shown in my window?

this is a thing which can be added at a later point, nothing really needed. Just great to be able to opt out if you have a room with many people.

**Comment by jkingsman** [comment]
There is an option to not receive images - are you looking for more of a visibility toggle? Receive them, but be able to decide when they are shown or not?

**Comment by Conver** [comment]
Where is this option?

And yes, more of an visibility toggle, so users can decide if they want to see them or not.

Maybe instead of just showing the images, then show a toggle button instead, where the images normal is, so they can choose to see it or not.

follow me?

**Comment by jkingsman** [comment]
The toggle is under the config, "Receive images." If someone sends an image while it's unchecked, you get the message "Image blocked by configuration." 

Yeah I track what you mean with a visibility toggle, and that may be more meaningful.

**Comment by Conver** [comment]
ah okay, its in the config file, I though you mean it was an option in the browser.

Well, that function is pretty useful too, should be changed to disallow images overall tho.
And if that images is allowed, then an option to opt out is shown?

**Comment by jkingsman** [comment]
No no it's an option in the browser.
![freestep testroom](https://cloud.githubusercontent.com/assets/2365891/6644663/2215f118-c973-11e4-857c-746a76523851.png)

**Comment by Conver** [comment]
ah okay, I see now..

and omg, I first now saw the option 'Recieve images', I was to fast here. 

Looks like it works like my description, so feel free to close this one.

although there is an typo: Recieve should be Receive

**Comment by jkingsman** [comment]
I just fixed it in the repo; pulling it down to prod in a couple minutes haha
