### ISSUE TITLE
Reword Sound Options

### ISSUE THREAD

**Issue by jkingsman** [jkingsman/FreeStep#61]
Sounds should not be made when the window is in focus. The options (and implied actions) should be:

* Play sound on nickname mention only
* Play sound on all messages

Both should only happen when the window is out of focus, and no sound should ever be made when the window is in focus. (Development of this issue is found at #58)

**Comment by jkingsman** [comment]
@Conver, I just committed the closing code on this. Go ahead and give it a spin if it's what you were looking for.

**Comment by Conver** [comment]
Great, I'll get the systems updated today.
