### ISSUE TITLE
Move/add FreeStep text

### ISSUE THREAD

**Issue by Conver** [jkingsman/FreeStep#62]
Make it editable to set the chat name (The one located in top corner) which is now "FreeStep" and link to same chat server url.

My suggestion is to make it editable in the server/client.js file to put own chat name there.
(which will be used else where aswell. meta etc)

and then put FreeStep information with real url to this repo or so in the bottom of same corner.
Maybe with license and copyright.

**Comment by jkingsman** [comment]
Sounds fair - I like putting the room link there. So you mean display the room name, or just have an editable region?

**Comment by Conver** [comment]
The room name is already there, down under that link. 
So it should be an name you can set for your overall chat name.

Example:
I have 2 room, called room1 and room2, that are on my chat server 'chatting', so the overall name would be 'chatting' in this case

**Comment by jkingsman** [comment]
Gotcha. Yeah I think that'd be doable.

**Comment by Conver** [comment]
Great.

That way, you'll also get a link to your website. Extra traffic is never bad :)

**Comment by jkingsman** [comment]
Accidentally commented on the wrong issue, but these settings are in client.js now. Brief details of var names are in the readme.
