### ISSUE TITLE
Include components folder

### ISSUE THREAD

**Issue by Conver** [jkingsman/FreeStep#63]
Include the components in this repo.

the components is not added to repo atm, so to get it working, you have to check all the files which are being includes, and go download / copy / paste it yourself.

**Comment by jkingsman** [comment]
Is 'npm install' not working for you?

**Comment by Conver** [comment]
I don't think so, I've been needing to create the folder and get all the files in the folder manually.

**Comment by jkingsman** [comment]
So you're talking about the node dependencies? They're intentionally not included because npm should take care of that. Lemme double check.

**Comment by Conver** [comment]
I mean the components which hold the bootstrap, css, js data etc, used on clients/website site

**Comment by jkingsman** [comment]
Ah - bower should be taking care of that as a post install task. You should see something like this at the bottom of your `npm install`:

```
> freestep@1.0.0 postinstall /home/jkingsman/test/FreeStep
> ./node_modules/bower/bin/bower install

bower cached        http://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip
bower validate      http://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip#*
bower new           version for http://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip#*
bower resolve       http://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip#*
bower download      http://crypto-js.googlecode.com/files/CryptoJS%20v3.1.2.zip
bower cached        git://github.com/jasny/bootstrap.git#3.1.3
bower validate      3.1.3 against git://github.com/jasny/bootstrap.git#*
bower cached        git://github.com/twbs/bootstrap.git#3.2.0
bower validate      3.2.0 against git://github.com/twbs/bootstrap.git#*
bower cached        git://github.com/jashkenas/underscore.git#1.7.0
bower validate      1.7.0 against git://github.com/jashkenas/underscore.git#*
[...]
```
And so forth.

If that's not appearing, a workaround would be to manually run bower (`./node_modules/bower/bin/bower install`), but that should definitely be showing up.

**Comment by Conver** [comment]
Maybe I didn't do bower install but npm install as the readme tells to do.

Maybe it would be better just include the folder?

**Comment by jkingsman** [comment]
I like to be able to keep them installed dynamically; it's best practice in my opinion. Committing them is possible but I think your issues may be an edge case -- I just tried it on a virgin VM and it installed fine.

The bower install is taken care of by npm; it installs bower as a dependency and then calls the binary directly. Does `./node_modules/bower/bin/bower` exist in your install?

**Comment by Conver** [comment]
I follow you, and would be the easiest way.

No, that does not exist in my install, on either of the servers.

**Comment by jkingsman** [comment]
interesting... so you used npm to install dependencies, but bower didn't make it in. Is there even a bower folder in `node_modules`?

**Comment by Conver** [comment]
Yes, I've used npm to install it.

No, there is no bower folder in there.

**Comment by jkingsman** [comment]
Now that is truly bizarre... that implies npm is failing to install an entire package.

Could you pastebomb me your `npm install` output, please? Just a test directory is fine; I just want to see what, if anything, npm thinks it's doing when it installs bower and tries to pull down the frontend dependencies.

**Comment by Conver** [comment]
Sure, give me a few minutes, I'll set up a server (Which same specs as the others), and install it there. if bower gets installed there, then I'll see if I can debug npm on the current servers

I dont have the best knowledge about npm, so I dont know if there is somewhere I can see the output already for the already installed systems?

**Comment by jkingsman** [comment]
Sounds good - and no, it's usually dumped to console unless errors occur.

**Comment by Conver** [comment]
Okay, I'll get you a dump ASAP.

ofc mate, Take your time, no stress hehe. I'm just adding issues as I see them. and those I can fix my self, I'll add a PR instead.

**Comment by Conver** [comment]
Okay, just ran the install on 2 different servers, and the bower folder is showing.
But the components folder is still not there.

I'll debug the other servers, which didn't get the bower folder, and see what got wrong there.

**Comment by jkingsman** [comment]
Hm. Alright. npm should install the bower folder, including the bower binary. npm then calls `./node_modules/bower/bin/bower install` which should put the components where they should go. You might also try manually running bower with the aforementioned command and see where that gets you.

**Comment by Conver** [comment]
I  might have found one issue:

**Comment by jkingsman** [comment]
Ahh gotcha. Yeah I usually run npm install as an unprivileged user. I would say to just run it as unprivileged, and see where that gets you -- if it solves it, I would be inclined to label this as `won't fix`, since bower isn't intended to be run as that.

**Comment by Conver** [comment]
I totally follow you.

I will try with unprivileged user. which I normally do. But in this case, where this is the only thing running on the server (Which controlled security, and enclosed network). 

Instead, let us add to the readme that it shouldn't be installed with root, so no one gets in the same position as me. I do know a thing or two about security on UNIX, so in my case it doesn't matter, because I can do it myself, but for other it would be a good idea to add it to readme.
