### ISSUE TITLE
Not able to start server this morning.

### ISSUE THREAD

**Issue by Conver** [jkingsman/FreeStep#64]
I dont know if it related to FreeStep or NodeJS.

But this morning when I tried to start the FreeStep server, I get the follow error:

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: listen EADDRNOTAVAIL
    at errnoException (net.js:905:11)
    at Server._listen2 (net.js:1024:19)
    at listen (net.js:1065:10)
    at net.js:1147:9
    at asyncCallback (dns.js:68:16)
    at Object.onanswer [as oncomplete] (dns.js:121:9)

**Comment by jkingsman** [comment]
This is most likely a node issue; it can't bind to the address. Make sure you're starting with admin privileges and that it isn't already running/there isn't an app on that port.

**Comment by jkingsman** [comment]
It could also be caused by a static IP in the configuration not matching the IP of the machine (if you're on DHCP or something).

**Comment by Conver** [comment]
Might have found the problem, not sure yet, waiting for some updates from a third-party. before I'll close this..

FreeStep is the only thing running on the server, with static IP.

**Comment by jkingsman** [comment]
Have you made sure that freestep isn't already running? `ps aux | grep node` will let you know.

**Comment by Conver** [comment]
Server has been rebooted and everything. nothing running.

**Comment by jkingsman** [comment]
Interesting... and the box's IP matches what you have in config (or its IP matches DNS lookup for that domain name)?

**Comment by jkingsman** [comment]
Hi! Back in the land of the living. Any luck with this issue?

**Comment by Conver** [comment]
ah, yes sorry forgot to report back.

It was an issue related to my domain.

**Comment by jkingsman** [comment]
Glad you got it resolved!
