### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Ashtor** [jkingsman/FreeStep#65]
Hi
1. I see that there is a limit when it comes to drag photos to a chatroom. i would like the limit of photosize to be increased to the max that a photo can have,so we can drag any photo
2. Commands:
- /kick <user> <reason> ("reason" is optional)
- /ban <user> <reason> <time in seconds> ("reason" and "time in seconds"  is optional)
- /unban <user>
- /owner <password> or /chown <password> ("password" is for setting the room you make as private and be owner of it).. make a red keysymbol on the person who become owner to indicate that the person is owner).
- /rem <roomname> or /del <roomname> (deletes the room permently)
- /mute <user> (to prevent the user from speaking)
- /topic <topic> (to set rules/info etc of the channel, only works for owned rooms after using the command /owner <password> or /chown <password>)
- /help (to display help about commands)

**Comment by jkingsman** [comment]
Hi! I've considered some more IRC-like commands, but I think it suits Freestep best to keep things as minimalistic as possible - the ethos of a secure, Spartan chatroom is important to the project, especially as it pertains to improving upon Chatstep. It would also mean that the server would need to keep track of user privileges, and I think it's best to keep the server as a know-nothing, user agnostic system. 

That being said, some might find these features useful, and while I don't have the time right now to undertake this large of an overhaul (the whole idea of the system is that users are very equal in control of the room, so changing that takes a massive soup to nuts reorganization), I would be open to someone working on a fork that I could merge in as a branch.

**Comment by jkingsman** [comment]
To add on - for your first point about photo limits, those can be adjusted in the server code quite easily. 

Also, with the topics, that requires data retention, which is probably the biggest no-no of this project. 

I hate to come out of the gate against your ideas, and I hope there's no hard feelings, but a lot of those commands are incompatible with pure anonymity to the server and other users, which is the guiding principle :/

Please don't be discouraged, and feel free to develop or have someone else develop these features for you! This project is open for forking to whomever wants to customize it or rebuild it for themselves. Ideas are wonderful things, even if they aren't able to be combined with this project right now.

**Comment by Ashtor** [comment]
There is 2 more things i want to say and/or ask.
1. Someone told me that he/she got disconnected from the chatsite every 10 minutes,but he/she dont get disconnected on other chatsites. Is that a bug? and if it is,it would be great to get it fixed. me myself haven't got that issue yet.
2.How come that when i show photo and write,the photos and text comes on the right side of the chat and not on the left side? and how do i fix that if its possible? And there should be an option to put the the message & photos on the left or right manually

**Comment by jkingsman** [comment]
I'm not sure what's going on with disconnections - if my server glitches or goes down, it will boot everyone, so that may be happening.

You messages, including images, come through on the left side by design.
