### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Ashtor** [jkingsman/FreeStep#66]
Hi
A quick question i need answer on quick.. When it comes to people chatting,share photos and all. Are they allowed to share anything? then i mean anything,no matter what it is without rooms getting banned? Can this chatsite b shut down or anything at all ?

**Comment by jkingsman** [comment]
FreeStep does its best to provide anonymity and not to log or track users. Chats are encrypted to keep them as safe as possible from prying eyes. However, if legally subpoenaed, I'll do my best to assist law enforcement however I can. If you're concerned about traffic loads or the sensitive nature of your chats, I suggest you set up your own installation on your own server.

**Comment by jkingsman** [comment]
In a more direct answer, if I have reason to believe that FreeStep is becoming a hub for illegal activity, I would consider shutting down the site. The current Freestep.net site is more of a demo site than anything else; my main goal is to distribute the source code, so if I was somehow made aware that I was enabling unsavory behavior, I would do my best to curb it, even if it meant taking the site down. If someone really needs the system, they should set it up on their own server.

**Comment by Ashtor** [comment]
Hi again. a last quick question about the issue #66. is there a way to prevent users from posting links and show photo? like change anything? i really dont want it to shut it down. i rather want you to fix the server so they can't post links or drag photo.

**Comment by jkingsman** [comment]
I think that being able to send pictures and links is a pretty important functionality - if you're running this on your own install, you can totally do that. 

If you're in a hurry, on your own installation, pictures can be pretty easily disabled by deleting this whole codeblock in `server.js`:

```js
   socket.on("dataSend", function (msg) {
      var currTime = Date.now();
      if(((currTime - lastImageSend) < 5000) && isRateLimited) {
         socket.emit("rateLimit");
      } else {
         lastImageSend = currTime;
         var type = 1;
         var name = socket.nickname;
         var data = [type, name, msg];
         io.sockets.in(socket.roomIn).emit("chat", data);
      }
   });
```

Detecting and blocking links is tricky, as handling and display of links is done entirely client side. You could just have the client not display them, but that doesn't stop them from getting to the client entirely. I don't think there's an easy solution for links.

**Comment by Ashtor** [comment]
well. just dont shut the site down no matter what. i love the site and i still want to use it and its so hard to find chatsite that is encrypted and anonymous.. specially one without TOS etc. if you know any chatsite like freestep wich has no rules at all,it would b great (exept chatstep,chatcrypt and cryptocat),, that would be all. just please dont shut it down no matter what.

**Comment by jkingsman** [comment]
Well I'm glad to hear that you like it - but if you need it so much, you should set up your own install.

Adding a ToS is actually on my todo list, sorry to disappoint you :/

**Comment by Ashtor** [comment]
Sorry for so many questions. but i need to know few things before i end this issue for the time being. 
1. Can u give me a link to the whole sourcecode for this?
2. What hosting site can i use wich is free where i can just upload the sourcecode easily with not so many programmes etc where the account on the hosting site doesnt expire at all?. thats the last 2 questions for now

**Comment by jkingsman** [comment]
No worries! Happy to answer questions. The whole source code is hosted on this site - GitHub. You can follow the directions in the [readme lower on this page](https://github.com/jkingsman/FreeStep) to grab it an set it up.

For hosting, you need something that supports node.js, which I don't think you'll find for free, sorry. You could definitely look around though.

**Comment by Ashtor** [comment]
Hi. this is very important and urgent and i got to say something and i have to report it . and I hate to ruin a good chatsite,but since its impossible to block photosharing and linksharing,i have to report it.. well u know that has something to do with underages people. u know. and it has been illegal activities on freestep.net  and the room they are in is girls. What you going to do?

**Comment by jkingsman** [comment]
Hi Ashtor please delete that comment. I will take the site down momentarily but please do not publicize the specific rooms as that may enable more users.

**Comment by Ashtor** [comment]
sorry about that. i just had to tell. but anyway. u got the message,just wanted to report it

**Comment by jkingsman** [comment]
Thank you for reporting that; the site is down now. I will put up a message later.

**Comment by Ashtor** [comment]
But since u have shut it down. have u thought about making a new chatsite like this,but prevent the user to share links and photos? and if so.. any extimated time when,if it ever happens?

**Comment by jkingsman** [comment]
Definitely not in the near future, if ever - life is pretty busy right now, sorry. You're welcome to base development of your own off my code though

**Comment by Ashtor** [comment]
just 1 more question and that is all. Do you know any other chatsites just like freestep.net ? and if so.. wich one and whats the site?

**Comment by jkingsman** [comment]
I wouldn't be comfortable making any recommendations.
