### ISSUE TITLE
bower install fails

### ISSUE THREAD

**Issue by dextersgenius** [jkingsman/FreeStep#72]
Ubuntu x64 16.04 LTS
---
[...]
bower resolved      https://github.com/FortAwesome/Font-Awesome.git#4.7.0    
bower resolved      https://github.com/jquery/jquery-dist.git#3.2.1          
bower resolved      https://github.com/twbs/bootstrap.git#3.3.7              
bower EHTTP         Status code of 404                                       
                                                                             
npm ERR! Linux 4.4.0-93-generic                                              
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"                     
npm ERR! node v4.2.6                                                         
npm ERR! npm  v3.5.2                                                         
npm ERR! code ELIFECYCLE                                                     
npm ERR! freestep@2.0.0 postinstall: `./node_modules/bower/bin/bower install`
npm ERR! Exit status 1                                                       
npm ERR!                                                                     
npm ERR! Failed at the freestep@2.0.0 postinstall script './node_modules/bowe
r/bin/bower install'.                                                        
npm ERR! Make sure you have the latest version of node.js and npm installed. 
npm ERR! If you do, this is most likely a problem with the freestep package, 
npm ERR! not with npm itself.                                                
npm ERR! Tell the author that this fails on your system:                     
npm ERR!     ./node_modules/bower/bin/bower install

**Comment by dextersgenius** [comment]
[npm-debug.log.txt](https://github.com/jkingsman/FreeStep/files/1299112/npm-debug.log.txt)

**Comment by jkingsman** [comment]
Whoops; looks like Google code going away broke some stuff. [Should be fixed now](https://github.com/jkingsman/FreeStep/blob/master/bower.json#L10).
